version: '3.0'

services:
  api:
    build:
      context: .
    container_name: routes
    ports:
      - "5000:5000"
    volumes:
      - ./application:/application
    env_file: .env
    restart: always